version: 2.1

executors:
  node-10:
    docker:
      - image: circleci/node:10
    environment:
      EXECUTOR_NAME: node-10
  node-12:
    docker:
      - image: circleci/node:12
    environment:
      EXECUTOR_NAME: node-12
  puppeteer:
    docker:
      - image: circleci/node:latest-browsers
    environment:
      EXECUTOR_NAME: puppeteer
workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          name: puppeteerEnv
          e: puppeteer
      - test-webpack-config-e2e:
          e: puppeteer
          requires:
            - puppeteerEnv
jobs:
  build:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    working_directory: ~/expo-cli
    steps:
      - checkout
      - run:
          # https://discuss.circleci.com/t/cannot-use-circle-yml-environment-variables-in-cache-keys/10994/20
          name: Configure env
          command: |
            echo "$EXECUTOR_NAME" > /tmp/.executor_name
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-{{ checksum "/tmp/.executor_name" }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Bootstrap (Link) Internal Dependencies
          command: yarn bootstrap
      - persist_to_workspace:
          root: '~'
          paths:
            - expo-cli
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-{{ checksum "/tmp/.executor_name" }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  test-webpack-config-e2e:
    parameters:
      e:
        type: executor
    executor: << parameters.e >>
    working_directory: ~/expo-cli/packages/webpack-config
    steps:
      - attach_workspace:
          at: '~'
      - run: yarn test:e2e
